/* eslint-disable  sonarjs/no-duplicate-string */
export const EventsService = {
  getEventsData() {
    return [
      {
        eventType: "product_investment_triggered",
        firstName: "James",
        lastName: "Doe",
        email: "james.doe@victorsmorgan.com",
        timestamp: "01/05/2023 08:10 am",
        productId: "45",
        productName: "L1 CAPITAL CATALYST FUND",
        poolId: "4",
        poolName: "L1 Capital",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "Dashboard",
        campaignName: "Live Portal- Catalyst Fund",
      },
      {
        eventType: "product_media_feed_viewed",
        firstName: "Alana",
        lastName: "Doe",
        email: "alana.doe@blackrock.com.au",
        timestamp: "05/05/2023 11:17 pm",
        productId: "4",
        productName: "L1 CAPITAL CATALYST FUND",
        poolId: "4",
        poolName: "L1 Capital",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName: "Live Portal- Catalyst Fund",
      },
      {
        eventType: "product_investment_started",
        firstName: "Kevin",
        lastName: "Vandy",
        email: "kevin.vandy@abc.com.au",
        timestamp: "09/05/2023 01:32 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "pool_media_feed_viewed",
        firstName: "Victoria",
        lastName: "Dunsford",
        email: "vic.dunsford@anz.com.au",
        timestamp: "02/05/2023 10:29 am",
        productId: "",
        productName: "",
        poolId: "2",
        poolName: "Victor Smorgon Partners",
        mediaTitle: "Livewire Podcast: The Rules of Investing - Peter Edwards",
        attachmentLabel:
          "Livewire Podcast: The Rules of Investing - Peter Edwards",
        pageName: "Dashboard",
        campaignName: "",
      },

      {
        eventType: "product_investment_viewed",
        firstName: "Joshua",
        lastName: "Rolluffs",
        email: "josh.Rolluffs@iress.com.au",
        timestamp: "10/05/2023 04:20 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Joshua",
        lastName: "Rolluffs",
        email: "josh.Rolluffs@iress.com.au",
        timestamp: "10/05/2023 04:48 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Jacob",
        lastName: "Anderson",
        email: "jacob.anderson@blackrock.com.au",
        timestamp: "10/05/2023 04:16 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_viewed",
        firstName: "Andy",
        lastName: "Maloney",
        email: "andy.maloney@blackrock.com.au",
        timestamp: "10/05/2023 03:41 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Andy",
        lastName: "Maloney",
        email: "andy.maloney@blackrock.com.au",
        timestamp: "10/05/2023 04:14 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Carl",
        lastName: "Cox",
        email: "carl.cox@blackrock.com.au",
        timestamp: "10/05/2023 04:18 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Peter",
        lastName: "Walker",
        email: "peter.walker@iress.com.au",
        timestamp: "10/05/2023 06:08 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Courtney",
        lastName: "Russel",
        email: "courtney.russel@iress.com.au",
        timestamp: "10/05/2023 06:14 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_triggered",
        firstName: "James",
        lastName: "Doe",
        email: "james.doe@victorsmorgan.com",
        timestamp: "01/05/2023 08:10 am",
        productId: "45",
        productName: "L1 CAPITAL CATALYST FUND",
        poolId: "4",
        poolName: "L1 Capital",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "Dashboard",
        campaignName: "Live Portal- Catalyst Fund",
      },
      {
        eventType: "product_media_feed_viewed",
        firstName: "Alana",
        lastName: "Doe",
        email: "alana.doe@blackrock.com.au",
        timestamp: "05/05/2023 11:17 pm",
        productId: "4",
        productName: "L1 CAPITAL CATALYST FUND",
        poolId: "4",
        poolName: "L1 Capital",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName: "Live Portal- Catalyst Fund",
      },
      {
        eventType: "pool_media_feed_viewed",
        firstName: "Victoria",
        lastName: "Dunsford",
        email: "vic.dunsford@anz.com.au",
        timestamp: "02/05/2023 10:29 am",
        productId: "",
        productName: "",
        poolId: "2",
        poolName: "Victor Smorgon Partners",
        mediaTitle: "Livewire Podcast: The Rules of Investing - Peter Edwards",
        attachmentLabel:
          "Livewire Podcast: The Rules of Investing - Peter Edwards",
        pageName: "Dashboard",
        campaignName: "",
      },

      {
        eventType: "product_investment_viewed",
        firstName: "Joshua",
        lastName: "Rolluffs",
        email: "josh.Rolluffs@iress.com.au",
        timestamp: "10/05/2023 04:20 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Joshua",
        lastName: "Rolluffs",
        email: "josh.Rolluffs@iress.com.au",
        timestamp: "10/05/2023 04:48 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Jacob",
        lastName: "Anderson",
        email: "jacob.anderson@blackrock.com.au",
        timestamp: "10/05/2023 04:16 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_viewed",
        firstName: "Andy",
        lastName: "Maloney",
        email: "andy.maloney@blackrock.com.au",
        timestamp: "10/05/2023 03:41 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Andy",
        lastName: "Maloney",
        email: "andy.maloney@blackrock.com.au",
        timestamp: "10/05/2023 04:14 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Carl",
        lastName: "Cox",
        email: "carl.cox@blackrock.com.au",
        timestamp: "10/05/2023 04:18 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Peter",
        lastName: "Walker",
        email: "peter.walker@iress.com.au",
        timestamp: "10/05/2023 06:08 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Courtney",
        lastName: "Russel",
        email: "courtney.russel@iress.com.au",
        timestamp: "10/05/2023 06:14 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_triggered",
        firstName: "James",
        lastName: "Doe",
        email: "james.doe@victorsmorgan.com",
        timestamp: "01/05/2023 08:10 am",
        productId: "45",
        productName: "L1 CAPITAL CATALYST FUND",
        poolId: "4",
        poolName: "L1 Capital",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "Dashboard",
        campaignName: "Live Portal- Catalyst Fund",
      },
      {
        eventType: "product_media_feed_viewed",
        firstName: "Alana",
        lastName: "Doe",
        email: "alana.doe@blackrock.com.au",
        timestamp: "05/05/2023 11:17 pm",
        productId: "4",
        productName: "L1 CAPITAL CATALYST FUND",
        poolId: "4",
        poolName: "L1 Capital",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName: "Live Portal- Catalyst Fund",
      },
      {
        eventType: "pool_media_feed_viewed",
        firstName: "Victoria",
        lastName: "Dunsford",
        email: "vic.dunsford@anz.com.au",
        timestamp: "02/05/2023 10:29 am",
        productId: "",
        productName: "",
        poolId: "2",
        poolName: "Victor Smorgon Partners",
        mediaTitle: "Livewire Podcast: The Rules of Investing - Peter Edwards",
        attachmentLabel:
          "Livewire Podcast: The Rules of Investing - Peter Edwards",
        pageName: "Dashboard",
        campaignName: "",
      },

      {
        eventType: "product_investment_viewed",
        firstName: "Joshua",
        lastName: "Rolluffs",
        email: "josh.Rolluffs@iress.com.au",
        timestamp: "10/05/2023 04:20 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Joshua",
        lastName: "Rolluffs",
        email: "josh.Rolluffs@iress.com.au",
        timestamp: "10/05/2023 04:48 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Jacob",
        lastName: "Anderson",
        email: "jacob.anderson@blackrock.com.au",
        timestamp: "10/05/2023 04:16 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_viewed",
        firstName: "Andy",
        lastName: "Maloney",
        email: "andy.maloney@blackrock.com.au",
        timestamp: "10/05/2023 03:41 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Andy",
        lastName: "Maloney",
        email: "andy.maloney@blackrock.com.au",
        timestamp: "10/05/2023 04:14 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Carl",
        lastName: "Cox",
        email: "carl.cox@blackrock.com.au",
        timestamp: "10/05/2023 04:18 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Peter",
        lastName: "Walker",
        email: "peter.walker@iress.com.au",
        timestamp: "10/05/2023 06:08 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Courtney",
        lastName: "Russel",
        email: "courtney.russel@iress.com.au",
        timestamp: "10/05/2023 06:14 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_triggered",
        firstName: "James",
        lastName: "Doe",
        email: "james.doe@victorsmorgan.com",
        timestamp: "01/05/2023 08:10 am",
        productId: "45",
        productName: "L1 CAPITAL CATALYST FUND",
        poolId: "4",
        poolName: "L1 Capital",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "Dashboard",
        campaignName: "Live Portal- Catalyst Fund",
      },
      {
        eventType: "product_media_feed_viewed",
        firstName: "Alana",
        lastName: "Doe",
        email: "alana.doe@blackrock.com.au",
        timestamp: "05/05/2023 11:17 pm",
        productId: "4",
        productName: "L1 CAPITAL CATALYST FUND",
        poolId: "4",
        poolName: "L1 Capital",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName: "Live Portal- Catalyst Fund",
      },
      {
        eventType: "pool_media_feed_viewed",
        firstName: "Victoria",
        lastName: "Dunsford",
        email: "vic.dunsford@anz.com.au",
        timestamp: "02/05/2023 10:29 am",
        productId: "",
        productName: "",
        poolId: "2",
        poolName: "Victor Smorgon Partners",
        mediaTitle: "Livewire Podcast: The Rules of Investing - Peter Edwards",
        attachmentLabel:
          "Livewire Podcast: The Rules of Investing - Peter Edwards",
        pageName: "Dashboard",
        campaignName: "",
      },

      {
        eventType: "product_investment_viewed",
        firstName: "Joshua",
        lastName: "Rolluffs",
        email: "josh.Rolluffs@iress.com.au",
        timestamp: "10/05/2023 04:20 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Joshua",
        lastName: "Rolluffs",
        email: "josh.Rolluffs@iress.com.au",
        timestamp: "10/05/2023 04:48 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Jacob",
        lastName: "Anderson",
        email: "jacob.anderson@blackrock.com.au",
        timestamp: "10/05/2023 04:16 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_viewed",
        firstName: "Andy",
        lastName: "Maloney",
        email: "andy.maloney@blackrock.com.au",
        timestamp: "10/05/2023 03:41 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Andy",
        lastName: "Maloney",
        email: "andy.maloney@blackrock.com.au",
        timestamp: "10/05/2023 04:14 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Carl",
        lastName: "Cox",
        email: "carl.cox@blackrock.com.au",
        timestamp: "10/05/2023 04:18 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Peter",
        lastName: "Walker",
        email: "peter.walker@iress.com.au",
        timestamp: "10/05/2023 06:08 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Courtney",
        lastName: "Russel",
        email: "courtney.russel@iress.com.au",
        timestamp: "10/05/2023 06:14 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_triggered",
        firstName: "James",
        lastName: "Doe",
        email: "james.doe@victorsmorgan.com",
        timestamp: "01/05/2023 08:10 am",
        productId: "45",
        productName: "L1 CAPITAL CATALYST FUND",
        poolId: "4",
        poolName: "L1 Capital",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "Dashboard",
        campaignName: "Live Portal- Catalyst Fund",
      },
      {
        eventType: "product_media_feed_viewed",
        firstName: "Alana",
        lastName: "Doe",
        email: "alana.doe@blackrock.com.au",
        timestamp: "05/05/2023 11:17 pm",
        productId: "4",
        productName: "L1 CAPITAL CATALYST FUND",
        poolId: "4",
        poolName: "L1 Capital",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName: "Live Portal- Catalyst Fund",
      },
      {
        eventType: "pool_media_feed_viewed",
        firstName: "Victoria",
        lastName: "Dunsford",
        email: "vic.dunsford@anz.com.au",
        timestamp: "02/05/2023 10:29 am",
        productId: "",
        productName: "",
        poolId: "2",
        poolName: "Victor Smorgon Partners",
        mediaTitle: "Livewire Podcast: The Rules of Investing - Peter Edwards",
        attachmentLabel:
          "Livewire Podcast: The Rules of Investing - Peter Edwards",
        pageName: "Dashboard",
        campaignName: "",
      },

      {
        eventType: "product_investment_viewed",
        firstName: "Joshua",
        lastName: "Rolluffs",
        email: "josh.Rolluffs@iress.com.au",
        timestamp: "10/05/2023 04:20 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Joshua",
        lastName: "Rolluffs",
        email: "josh.Rolluffs@iress.com.au",
        timestamp: "10/05/2023 04:48 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Jacob",
        lastName: "Anderson",
        email: "jacob.anderson@blackrock.com.au",
        timestamp: "10/05/2023 04:16 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_viewed",
        firstName: "Andy",
        lastName: "Maloney",
        email: "andy.maloney@blackrock.com.au",
        timestamp: "10/05/2023 03:41 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Andy",
        lastName: "Maloney",
        email: "andy.maloney@blackrock.com.au",
        timestamp: "10/05/2023 04:14 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Carl",
        lastName: "Cox",
        email: "carl.cox@blackrock.com.au",
        timestamp: "10/05/2023 04:18 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Peter",
        lastName: "Walker",
        email: "peter.walker@iress.com.au",
        timestamp: "10/05/2023 06:08 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
      {
        eventType: "product_investment_started",
        firstName: "Courtney",
        lastName: "Russel",
        email: "courtney.russel@iress.com.au",
        timestamp: "10/05/2023 06:14 pm",
        productId: "3",
        productName: "COOLABAH FLOATING-RATE HIGH YIELD FUND",
        poolId: "",
        poolName: "",
        mediaTitle: "",
        attachmentLabel: "",
        pageName: "",
        campaignName:
          "Live- Coolabah Floating Rate High Yield Fund Assisted Investor Class",
      },
    ];
  },

  getEvents() {
    return Promise.resolve(this.getEventsData());
  },
};

/* eslint-disable  sonarjs/no-duplicate-string */
